remote_theme: "mmistakes/minimal-mistakes@4.24.0"
theme: minimal-mistakes-jekyll

# Plugins
plugins:
  - jekyll-include-cache

# Your site title and description
title: Nathan Storey
description: "Director of Data Governance | NYC Office of Technology & Innovation"

# Disable RSS feed in footer
atom_feed:
  hide: true

# Optional: Define navigation links
# This will be configured more in detail below
