remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins
plugins:
  - jekyll-include-cache

# Your site title and description
title: Nathan Storey
description: "Director of Data Governance | NYC Office of Technology & Innovation"

# Optional: Define navigation links
# This will be configured more in detail below
